In [2]:
from groundingdino.util.inference import load_model, load_image, predict, annotate, batch_predict
import cv2
import torch

model = load_model("groundingdino/config/GroundingDINO_SwinT_OGC.py", "groundingdino_swint_ogc.pth")
IMAGE_PATH = "/Users/derek/Desktop/Drone-detection-dataset/output_frames/V_DRONE_001/frame_0000.jpg"
IMAGE_PATH = "/Users/derek/Desktop/multiple_planes.jpg"
TEXT_PROMPT = "flying object"
BOX_TRESHOLD = 0.35
TEXT_TRESHOLD = 0.25

image_source, image = load_image(IMAGE_PATH)

# boxes, logits, phrases = predict(
#     model=model,
#     # preprocessed_images=image.unsqueeze(0),
#     image=image,
#     caption=TEXT_PROMPT,
#     box_threshold=BOX_TRESHOLD,
#     text_threshold=TEXT_TRESHOLD,
#     device="cpu"
# )
images = torch.stack([image, image])
boxes, logits, boxes_to_im = batch_predict(
    model=model,
    preprocessed_images=images,
    caption=TEXT_PROMPT,
    box_threshold=BOX_TRESHOLD,
    text_threshold=TEXT_TRESHOLD,
    device="cpu"
)

annotated_frame = annotate(image_source=image_source, boxes=boxes, logits=logits, phrases=["object"])
cv2.imwrite("annotated_image.jpg", annotated_frame)

final text_encoder_type: bert-base-uncased


SupervisionWarnings: annotate is deprecated: `BoxAnnotator` is deprecated and will be removed in `supervision-0.22.0`. Use `BoundingBoxAnnotator` and `LabelAnnotator` instead


True

In [3]:
boxes.shape

torch.Size([4, 4])

In [4]:
boxes_to_im

[0, 0, 1, 1]

In [1]:
from groundingdino.util.inference import Model


model = Model(
    model_config_path="groundingdino/config/GroundingDINO_SwinT_OGC.py",
    model_checkpoint_path="groundingdino_swint_ogc.pth",
    device="cpu"
)
IMAGE_PATH = "/Users/derek/Desktop/Drone-detection-dataset/output_frames/V_DRONE_001/frame_0000.jpg"
TEXT_PROMPT = "flying object"
BOX_TRESHOLD = 0.35
TEXT_TRESHOLD = 0.25

image = Model.preprocess_image_path(IMAGE_PATH)


model.predict_with_caption(
    image=image,
    caption=TEXT_PROMPT,
    box_threshold=BOX_TRESHOLD,
    text_threshold=TEXT_TRESHOLD,
)

final text_encoder_type: bert-base-uncased


tensor([[2.0107e+02, 3.7061e-01, 4.9936e+01, 1.5729e-01]]) 3 800


(Detections(xyxy=array([[176.09795   ,   0.2919684 , 226.03407   ,   0.44925904]],
       dtype=float32), mask=None, confidence=array([0.7914222], dtype=float32), class_id=None, tracker_id=None, data={}),
 ['object'])

In [3]:
image

tensor([[[-0.7993, -0.7993, -0.7993,  ..., -0.8849, -0.8849, -0.8849],
         [-0.7993, -0.7993, -0.7993,  ..., -0.8849, -0.8849, -0.8849],
         [-0.7993, -0.7993, -0.7993,  ..., -0.8849, -0.8849, -0.8849],
         ...,
         [-0.9877, -0.9705, -0.9534,  ..., -1.1075, -1.1418, -1.1589],
         [-1.0048, -0.9877, -0.9705,  ..., -1.1247, -1.1075, -1.0733],
         [-1.0048, -0.9877, -0.9705,  ..., -1.1247, -1.0733, -1.0219]],

        [[ 0.1176,  0.1176,  0.1176,  ..., -0.0574, -0.0574, -0.0574],
         [ 0.1176,  0.1176,  0.1176,  ..., -0.0574, -0.0574, -0.0574],
         [ 0.1176,  0.1176,  0.1176,  ..., -0.0574, -0.0574, -0.0574],
         ...,
         [-0.6176, -0.6001, -0.5826,  ..., -0.8277, -0.8627, -0.8803],
         [-0.6352, -0.6176, -0.6001,  ..., -0.8452, -0.8277, -0.7927],
         [-0.6352, -0.6176, -0.6001,  ..., -0.8452, -0.7927, -0.7402]],

        [[ 1.2457,  1.2457,  1.2457,  ...,  1.0714,  1.0714,  1.0714],
         [ 1.2457,  1.2457,  1.2457,  ...,  1

In [5]:
image

tensor([[[-0.7993, -0.7993, -0.7993,  ..., -0.8849, -0.8849, -0.8849],
         [-0.7993, -0.7993, -0.7993,  ..., -0.8849, -0.8849, -0.8849],
         [-0.7993, -0.7993, -0.7993,  ..., -0.8849, -0.8849, -0.8849],
         ...,
         [-0.9877, -0.9705, -0.9534,  ..., -1.1075, -1.1418, -1.1589],
         [-1.0048, -0.9877, -0.9705,  ..., -1.1247, -1.1075, -1.0733],
         [-1.0048, -0.9877, -0.9705,  ..., -1.1247, -1.0733, -1.0219]],

        [[ 0.1176,  0.1176,  0.1176,  ..., -0.0574, -0.0574, -0.0574],
         [ 0.1176,  0.1176,  0.1176,  ..., -0.0574, -0.0574, -0.0574],
         [ 0.1176,  0.1176,  0.1176,  ..., -0.0574, -0.0574, -0.0574],
         ...,
         [-0.6176, -0.6001, -0.5826,  ..., -0.8277, -0.8627, -0.8803],
         [-0.6352, -0.6176, -0.6001,  ..., -0.8452, -0.8277, -0.7927],
         [-0.6352, -0.6176, -0.6001,  ..., -0.8452, -0.7927, -0.7402]],

        [[ 1.2457,  1.2457,  1.2457,  ...,  1.0714,  1.0714,  1.0714],
         [ 1.2457,  1.2457,  1.2457,  ...,  1